---

- name: Ensure repo in place for RHEL
  template:
    src: Gluster.repo.j2
    dest: /etc/yum.repos.d/Gluster.repo
  vars:
    rhel_gluster_minor_version: "10"
  when: ansible_distribution == "RedHat"

- name: Ensure CentOS prerequisites in place
  yum:
    name:
      - "centos-release-gluster{{ glusterfs_default_release }}"
    state: present
  when: ansible_distribution == "CentOS"
  tags:
    - latest

- name: Install Packages
  yum:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present
  tags:
    - latest
