---
- name: Ensure ghostscript installed
  package:
    name: ghostscript
    state: latest

- name: Ensure old ImageMagick NOT installed from Meza RPM (RedHat/CentOS only)
  yum:
    name: imagemagick-7.0.3-1.x86_64
    state: absent
  when: ansible_os_family == 'RedHat'

- name: Ensure ImageMagick at latest version (RedHat/CentOS only)
  yum:
    name:
      - ImageMagick
      - ImageMagick-devel
    state: latest
  tags:
    - latest
  when: ansible_os_family == 'RedHat'

- name: Ensure Imagemagick installed (Debian only)
  apt:
    name: imagemagick
    state: latest
  when: ansible_os_family == 'Debian'

- name: Copy xpdf bin64 files to /usr/local/bin
  copy:
    src: xpdf-3.04-bin64/
    dest: /usr/local/bin/
